"""Add report file path to LabResult

Revision ID: 3adabd088834
Revises: 6e59af1e0f68
Create Date: 2026-05-03 07:22:35.673465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adabd088834'
down_revision = '6e59af1e0f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_file_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_column('report_file_path')

    # ### end Alembic commands ###
