"""add admin_profiles table

Revision ID: 5202946536fa
Revises: 3adabd088834
Create Date: 2026-05-04 11:38:50.969965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5202946536fa'
down_revision = '3adabd088834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_profiles_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_profiles_id'))

    op.drop_table('admin_profiles')
    # ### end Alembic commands ###
