"""Update LabResult model

Revision ID: 6e59af1e0f68
Revises: 0d60cf409863
Create Date: 2026-05-02 22:56:23.346114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e59af1e0f68'
down_revision = '0d60cf409863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('released_to_patient', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_column('released_to_patient')
        batch_op.drop_column('published_at')
        batch_op.drop_column('doctor_comment')

    # ### end Alembic commands ###
