"""Removed unique constraint to allow re-booking

Revision ID: f2e087805730
Revises: 876a6d569d71
Create Date: 2026-04-28 13:20:29.376182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e087805730'
down_revision = '876a6d569d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointments_availability_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('appointments_availability_id_key'), ['availability_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
